### ISSUE TITLE
yarn codegen - /bin/sh: graph: command not found

### ISSUE THREAD

**Issue by whittlem** [pancakeswap/pancake-subgraph#105]
I'm following the setup instructions and receiving an error.

    exchange % yarn codegen        
    yarn run v1.22.10
    $ graph codegen subgraph.yaml
    /bin/sh: graph: command not found
    error Command failed with exit code 127.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I can't seem to find anything online to help resolve this. I tried "npm i -g graph" but that didn't help.

Any ideas? I'm using macOS Big Slur Version 11.5.2

**Comment by ChefKai** [comment]
Hello, you need to install [graphprotocol/graph-cli](https://github.com/graphprotocol/graph-cli) globally in order to run these commands, I'll add it to the README, you can also find more information of [TheGraph documentation](https://thegraph.com/docs/developer/quick-start#3-initialize-a-new-subgraph).

**Comment by whittlem** [comment]
@ChefKai, thanks that worked.

Just FYI, I had to run "yarn" on its own before the "yarn build" step. It may be worth adding it to your steps.

For this step, "Run graph auth --product hosted-service '<ACCESS_TOKEN>'". Where does the <ACCESS_TOKEN> come form?

**Comment by ChefKai** [comment]
> @ChefKai, thanks that worked.
> 
> Just FYI, I had to run "yarn" on its own before the "yarn build" step. It may be worth adding it to your steps.
> 
> For this step, "Run graph auth --product hosted-service '<ACCESS_TOKEN>'". Where does the <ACCESS_TOKEN> come form?

Please, refer to [TheGraph documentation](https://thegraph.com/docs/legacyexplorer/deploy-subgraph-hosted).

**Comment by ChefKai** [comment]
> Hello, you need to install [graphprotocol/graph-cli](https://github.com/graphprotocol/graph-cli) globally in order to run these commands, I'll add it to the README, you can also find more information of [TheGraph documentation](https://thegraph.com/docs/developer/quick-start#3-initialize-a-new-subgraph).

This issue has been mentioned in the README with #122 to help setup be easier to understand, thanks for your feedback!
