### ISSUE TITLE
Cannot use pancake-subgraph to get special pair/token data

### ISSUE THREAD

**Issue by yyxx2z** [pancakeswap/pancake-subgraph#108]
Hey guys, when I use your [Pairs](https://thegraph.com/legacy-explorer/subgraph/pancakeswap/pairs) query to search this contract address
> [0x8c83E7AEF5116bE215223d3688a2f5dc4c7F241b](https://www.bscscan.com/address/0x8c83e7aef5116be215223d3688a2f5dc4c7f241b)

It always give the `null` response.
So can you tell me what happened in the case.

That following is my SQL:
```
{
  token (id: "0x8c83E7AEF5116bE215223d3688a2f5dc4c7F241b") {
    name
    id
  }
}

// or

{
  pair (id: "0x8c83E7AEF5116bE215223d3688a2f5dc4c7F241b") {
    name
    id
  }
}
```

**Comment by ChefKai** [comment]
Hello, this is because you are trying to fetch a `Token` entity while your address is referring to a `Pair` / Pancake LP's. The following query is working, please have a look at it:

GraphQL query:

```graphql
{
  pair (id: "0x8c83e7aef5116be215223d3688a2f5dc4c7f241b") {
    id
    name
  }
  token (id: "0x765b85839717ebfc84378b83381a4814897a0506") {
    id
    name
  }
}
```

Response:

```json
{
  "data": {
    "pair": {
      "id": "0x8c83e7aef5116be215223d3688a2f5dc4c7f241b",
      "name": "REI-BUSD"
    },
    "token": {
      "id": "0x765b85839717ebfc84378b83381a4814897a0506",
      "name": "Zerogoki Token"
    }
  }
}
```

Note: Please keep in mind that all addresses are in lowercase.

**Comment by yyxx2z** [comment]
Thx a lot

**Comment by yyxx2z** [comment]
Sorry to bother you again.
I could not use [this subgraph](https://thegraph.com/legacy-explorer/subgraph/pancakeswap/pairs?selected=playground) to get Wault contract data. 
GraphQL:
```
{
  pair(id: "0x4b31d95654300cbe8ce3fe2b2ec5c6d2929ae7a6") {
    id
    name
  }
}
```
Response:
```
{
  "data": {
    "pair": null
  }
}
```

I am try to find one subgraph on thegraph to search from whole BSC.  I only find this subgraph but your guys archived the github repository:
> https://github.com/pancakeswap/pancake-v2-subgraph

So could you tell me how to get Wault contract data by thegraph?
It will very helpful to me. Thanks.
