### ISSUE TITLE
prediction v2 subgraph is in error

### ISSUE THREAD

**Issue by HikaGenji** [pancakeswap/pancake-subgraph#114]
https://thegraph.com/legacy-explorer/subgraph/pancakeswap/prediction-v2?selected=logs

16/09/2021, 04:17:34

ERROR

Subgraph instance failed to run: Error while processing block stream for a subgraph: store error: too many notifications in the NOTIFY queue, code: SubgraphSyncingFailure

**Comment by ChefKai** [comment]
This is an issue with TheGraph hosted service, the subgraph has been restarted and is at the latest block

**Comment by ChefKai** [comment]
See the related incident at TheGraph status page: https://status.thegraph.com/incidents/mpk3rcbyhp10
