### ISSUE TITLE
Pancakeswap prediction Bet subgraph method

### ISSUE THREAD

**Issue by gguiomar** [pancakeswap/pancake-subgraph#117]
Been trying to understand how the subgraph method works for triggering a bet on the pancakeswap predictions.

Currently I'm sending the following query:

>   bet(id: 6062) {
    id
    hash
    block
    amount
    claimedAt
    position:Bear 
}

but it outputs the following

>  "message": "Type `Bet` has no field `Bear`"

which is a bit weird as it's one of the accepted names for position.

What am I doing wrong?

**Comment by ChefKai** [comment]
Hello, you cannot "trigger" a bet using a subgraph as they are read-only, I suggest reading more about [TheGraph](https://thegraph.com/docs/about/introduction#what-the-graph-is) and what you can do with them.

If you want to interact with the Prediction(s) smart contract, use Web3.js/ethers/...
