### ISSUE TITLE
Subgraph for predictions v2 is broken

### ISSUE THREAD

**Issue by milewski** [pancakeswap/pancake-subgraph#162]
https://thegraph.com/hosted-service/subgraph/pancakeswap/prediction-v2

![image](https://user-images.githubusercontent.com/2874967/164703713-046622e2-140d-450f-b223-2966454f4622.png)
![image](https://user-images.githubusercontent.com/2874967/164703792-ff801e93-d16d-478a-badd-99ea44121f36.png)

**Comment by Supportprotocol** [comment]
Kindly open this live chat link to talk to the customer service directly on your issue  https://direct.lc.chat/14232768/
