### ISSUE TITLE
Can't get exchange data using local graph-node

### ISSUE THREAD

**Issue by waybeforenow** [pancakeswap/pancake-subgraph#30]
I am running a local graph-node for testing using the latest version of the [Docker container](https://hub.docker.com/r/graphprotocol/graph-node). It's pointed at a BSC mainnet full node.

I've followed the steps in the README to deploy the subgraphs in this repo. Since I'm using a local graph-node and not the production one, I've modified it so it looks more like:
```
yarn run codegen:[subgraph]
yarn run build:[subgraph]
npx graph create --node http://graph-node.internal:8020/ pancakeswap/[subgraph]
npx graph deploy --debug --ipfs http://ipfs-host.internal:5001 --node http://graph-node.internal:8020/ pancakeswap/[subgraph] subgraphs/[subgraph].yaml
```

When deploying `blocks` and `dexcandles`, I can see the data come through in the GraphiQL explorer after it's indexed by the graph node. However, after deploying `exchange` and waiting some time, no `pairs` show up at all, e.g.

```graphql
{
  pairs(first:500){
    id
    token0 {
      id
    }
    token1 {
      id
    }
  } 
}
```
gives the response
```json
{
  "data": {
    "pairs": []
  }
}
```

I did notice that there is a PR for a new version of the `exchange` subgraph, so is it possible that the current one from the `master` branch doesn't work anymore? I'm new to using The Graph and I don't know how to debug it well, but let me know if there's any relevant information I should include, or any pointers on getting started inspecting the internal state from the graph-node. It would be very useful. Thanks!

**Comment by maurodelazeri** [comment]
it is working just fine... most likely the node that you are pulling the data is not a full node (archive mode)

here an example of the testnet from the master repo as is ![](https://i.imgur.com/MOYA82N.png)

**Comment by waybeforenow** [comment]
Thank you! I switched to an archive node, and it's indexing the subgraph properly now. 🎉

**Comment by fxmarty** [comment]
> Thank you! I switched to an archive node, and it's indexing the subgraph properly now. tada

@waybeforenow Could you give details on what you did change? Many thanks!

**Comment by waybeforenow** [comment]
> 
> 
> > Thank you! I switched to an archive node, and it's indexing the subgraph properly now. tada
> 
> @waybeforenow Could you give details on what you did change? Many thanks!

You'll need to make sure that your `graph-node` is pointed at a BSC node that has `--gcmode archive` in its command line flags. Otherwise the node will delete some intermediate contract state data that's necessary to build the subgraph.
