### ISSUE TITLE
Subgraph out of sync 

### ISSUE THREAD

**Issue by mmontes11** [pancakeswap/pancake-subgraph#37]
The oficial subgraph seems to be out of sync:
https://thegraph.com/explorer/subgraph/pancakeswap/exchange

I've also tried to deploy my own subgraph with no luck:
https://thegraph.com/explorer/subgraph/mmontes11/pancakeswap

See also:
https://github.com/pancakeswap/pancake-v2-subgraph/issues/7

Any updates on this?

**Comment by maurodelazeri** [comment]
yeaa, I deployed and same thing.., but this is a problem with thegraph

**Comment by qbig** [comment]
× Failed to deploy to Graph node https://api.thegraph.com/deploy/: Ethereum nodes for network bsc are missing the following capabilities: archive, traces

**Comment by nicoasdd** [comment]
So guys is it an issue with the graph? so sad :(

**Comment by ChefKai** [comment]
Follow-up available on #50

**Comment by ChefKai** [comment]
Hello, yes, finally an update on this; we now have finished migrating the `exchange` subgraph to StreamingFast, to allow you to access PancakeSwap v2 data!

Endpoint: https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2

Article: https://pancakeswap.medium.com/pancakeswap-info-relaunch-in-partnership-with-150-000-bounty-winner-streamingfast-f7892559d388

**Comment by segersniels** [comment]
> Hello, yes, finally an update on this; we now have finished migrating the `exchange` subgraph to StreamingFast, to allow you to access PancakeSwap v2 data!
> 
> Endpoint: https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2
> 
> Article: https://pancakeswap.medium.com/pancakeswap-info-relaunch-in-partnership-with-150-000-bounty-winner-streamingfast-f7892559d388

How do you even perform requests to that streamingfast subgraph? It seems like it explicitly requires the origin and referer header to be set to `https://pancakeswap.info` before you can perform any requests. Which works fine for something like `curl` but screws with eg. `node-fetch` where the origin header seemingly doesn't apply. Would love some assistance!

**Comment by nicoasdd** [comment]
> Hello, yes, finally an update on this; we now have finished migrating the `exchange` subgraph to StreamingFast, to allow you to access PancakeSwap v2 data!
> 
> Endpoint: https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2
> 
> Article: https://pancakeswap.medium.com/pancakeswap-info-relaunch-in-partnership-with-150-000-bounty-winner-streamingfast-f7892559d388

Sorry pretty new to Graph QL, is there any place where I can check for the Schema? or example queries?

**Comment by this-username-is-taken** [comment]
@tambu22 if you open up the endpoint https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2, on the right, there is a document explorer panel where you can drill into the schema
