### ISSUE TITLE
Can't find a token

### ISSUE THREAD

**Issue by sarahs3** [pancakeswap/pancake-subgraph#71]
Hi, 
I work on a application that need to get the current price of the CateCoin on Pancakeswap. 

I can't find this token in the Subgraph datas. 

The data provided by the subgraph is that of PancakeSwap V1 and not of V2?

Thank you in advance :)

**Comment by ChefKai** [comment]
Hello, the data provided on TheGraph for the `exchange` subgraph is only for PancakeSwap v1, as there are multiple issues on the Hosted service, we have chosen to offer PancakeSwap v2 data by using StreamingFast; if you wish to access this data, please refer to this article, and endpoint.

Endpoint: https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2

Article: https://pancakeswap.medium.com/pancakeswap-info-relaunch-in-partnership-with-150-000-bounty-winner-streamingfast-f7892559d388

**Comment by sarahs3** [comment]
thank's you :) i will look that :)
