### ISSUE TITLE
Exchange subgraph is out of sync

### ISSUE THREAD

**Issue by maaz28** [pancakeswap/pancake-subgraph#72]
Pairs, timelock, blocks and other subgraphs are 100% synced, though Exchange subgraph [https://thegraph.com/explorer/subgraph/pancakeswap/exchange](https://thegraph.com/explorer/subgraph/pancakeswap/exchange) is not yet synced completely.

Is the team working on it or we need to find alternative solutions?

**Comment by vaibhavk97** [comment]
@ChefKai kindly suggest a solution for this.

**Comment by ChefKai** [comment]
Hello, unfortunately we cannot use TheGraph actually to sync the `exchange` subgraph, this is why we are using StreamingFast to provide this data to you. The `exchange` subgraph currently on TheGraph is for PancakeSwap v1.

Endpoint: https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2

Article: https://pancakeswap.medium.com/pancakeswap-info-relaunch-in-partnership-with-150-000-bounty-winner-streamingfast-f7892559d388
