### ISSUE TITLE
Exchange Subgraph is out of sync

### ISSUE THREAD

**Issue by JanOwiesniak** [pancakeswap/pancake-subgraph#74]
https://thegraph.com/explorer/subgraph/pancakeswap/exchange
<img width="1341" alt="Screenshot 2021-06-19 at 13 45 47" src="https://user-images.githubusercontent.com/213214/122641294-adbf4580-d104-11eb-8908-0c5df25f35e6.png">

The 70.2% is not moving so 100% will never be reached.

**Comment by ChefKai** [comment]
Hello, unfortunately we cannot use TheGraph actually to sync the `exchange` subgraph, this is why we are using StreamingFast to provide this data to you. The `exchange` subgraph currently on TheGraph is for PancakeSwap v1.

Endpoint: https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2

Article: https://pancakeswap.medium.com/pancakeswap-info-relaunch-in-partnership-with-150-000-bounty-winner-streamingfast-f7892559d388

**Comment by dipespandey** [comment]
Hi @ChefKai, the streamingfast link is not working for me anymore. 
I get Timed Out error. Can you please help?
The error: `504 Server Error: Gateway Time-out for url: https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2`

**Comment by hantengyuan** [comment]
@dipespandey  Hi, I have the same problem, how did you solve it, thanks

**Comment by fhrryDeveloper** [comment]
Hi Everyone.
I have same error **`(504 Server Error: Gateway Time-out for url: https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2)`**
Who has solution?

**Comment by michaelFranciscoOV** [comment]
same

**Comment by reeezzzz** [comment]
I am using   (https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2)       it   lately has been giving me this 
  "errors": [
    {
      "message": "panic processing query: only derived fields can lead to multiple children here"

**Comment by selimekim94** [comment]
Could you please fix the "message": "panic processing query: only derived fields can lead to multiple children here" error? I'm using https://bsc.streamingfast.io/subgraphs/name/pancakeswap/exchange-v2

**Comment by reeezzzz** [comment]
while waiting for it to be fully back and working try check this one out [](https://api.thegraph.com/subgraphs/name/elrakabawi/pancakeswap)

**Comment by reeezzzz** [comment]
while waiting for it to be fully back and working try check this one out [https://api.thegraph.com/subgraphs/name/elrakabawi/pancakeswap](url)

**Comment by reeezzzz** [comment]
try https://api.thegraph.com/subgraphs/name/ookvic/pancakeswap-v2   it's a
hosted service not official but it's  slow , also disregard  the prior
earlier post I made on github  that was a mistake
